site_name: Gthulhu
site_description: Cloud-native workload optimization scheduler based on Linux Scheduler Extension
site_url: https://gthulhu.github.io/
repo_url: https://github.com/Gthulhu/Gthulhu
edit_uri: https://github.com/Gthulhu/docs/blob/main/docs/

nav:
  - Home: 
    - English: index.md
    - 中文: index.zh.md
  - Get Started:
    - Installation:
      - English: installation.en.md
      - 中文: installation.md
    - k8s deployment:
      - English: k8s.en.md
      - 中文: k8s.md
    - How It Works:
      - English: how-it-works.en.md
      - 中文: how-it-works.md
    - Project Goals:
      - English: project-goals.en.md
      - 中文: project-goals.md
    - Development History:
      - English: development-history.en.md
      - 中文: development-history.md
    - API Reference:
      - English: api-reference.en.md
      - 中文: api-reference.md
    - FAQ:
      - English: faq.en.md
      - 中文: faq.md
    - Mentioned:
      - English: mentioned.en.md
      - 中文: mentioned.md
  - Contributing:
    - English: contributing.en.md
    - 中文: contributing.md

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: 
        - en
        - zh
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
    property: G-T0RWMB3KJM
