site_name: Gthulhu
site_description: Cloud-native workload optimization scheduler based on Linux Scheduler Extension
site_url: https://gthulhu.github.io/docs/
repo_url: https://github.com/Gthulhu/Gthulhu
edit_uri: https://github.com/Gthulhu/docs/blob/main/docs/

nav:
  - Home: index.md
  - Get Started:
    - Installation: installation.md
    - K8s Deployment: k8s.md
    - How It Works: how-it-works.md
    - Project Goals: project-goals.md
    - Development History: development-history.md
    - API Reference: api-reference.md
    - FAQ: faq.md
    - Mentioned: mentioned.md
  - Contributing: contributing.md

theme:
  name: material
  language: en
  logo: https://raw.githubusercontent.com/Gthulhu/Gthulhu/main/assets/logo.png
  # favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: 
        - en
        - zh
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首頁
            Get Started: 開始使用
            Installation: 安裝
            K8s Deployment: K8s 部署
            How It Works: 運作原理
            Project Goals: 專案目標
            Development History: 開發歷史
            API Reference: API 參考
            FAQ: 常見問題
            Mentioned: 相關報導
            Contributing: 貢獻指南
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-T0RWMB3KJM
