site_name: Gthulhu & SCX GoLand Core Documentation
site_description: Cloud-native workload optimization scheduler based on Linux Scheduler Extension
site_url: https://gthulhu.github.io/

nav:
  - Home: 
    - 中文: index.md
    - English: index.en.md
  - Installation:
    - 中文: installation.md  
    - English: installation.en.md
  - How It Works:
    - 中文: how-it-works.md
    - English: how-it-works.en.md
  - Project Goals:
    - 中文: project-goals.md
    - English: project-goals.en.md
  - API Reference:
    - 中文: api-reference.md
    - English: api-reference.en.md
  - FAQ:
    - 中文: faq.md
    - English: faq.en.md
  - Contributing:
    - 中文: contributing.md
    - English: contributing.en.md

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: 
        - zh
        - en
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
